name: sirtuin

on: [pull_request, merge_group]

jobs:
  workflow:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        poetry-version: [1.3, 1.4, 1.5]
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ./.venv/
          key: sirtuin-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Setup Poetry ${{ matrix.poetry-version }}
        run: curl -sSL https://install.python-poetry.org | python3 - --version ${{ matrix.poetry-version }}

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: poetry install --sync --with dev,types

      - name: Run Black
        run: make black

      - name: Run Isort
        run: make isort

      - name: Run MyPy
        run: make mypy

      - name: Run Ruff
        run: make ruff

      - name: Run Pytest
        run: make pytest
